name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master
  schedule:
    # Every 15 mins
    - cron: "*/15 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      working-directory-scraper: ./scraper
      working-directory-app: ./app
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies (Scraper)
        working-directory: ${{env.working-directory-scraper}}
        run: yarn install

      - name: Scrape
        working-directory: ${{env.working-directory-scraper}}
        run: yarn scrape

      - name: Install dependencies (App)
        working-directory: ${{env.working-directory-app}}
        run: yarn install

      - name: Build App
        working-directory: ${{env.working-directory-app}}
        run: yarn build

      - name: Deploy App
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ${{env.working-directory-app}}/build
