name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master
  schedule:
    # Every 15 mins
    - cron: "*/15 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: yarn install

      - name: Scrape
        run: yarn workspace scraper scrape

      - name: Build App
        run: yarn workspace app build

      - name: Deploy App
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./app/build
